[build]
target = "i686-pc-windows-gnu"

[target.i686-pc-windows-gnu]
rustflags = [
    "--remap-path-prefix", "${HOME}=~",
    "-Clink-arg=-Wl,--no-insert-timestamp",
]

[target.i686-pc-windows-msvc]
rustflags = [
    "--remap-path-prefix", "${HOME}=~",
]
